#+TITLE: The Border Patrol Website.

The Border Patrol website is a static website using [[http://jaspervdj.be/hakyll/][Haykll]], and is published in the meantime using GitHub.

Hakyll generates a custom executable for transforming the markdown pages, and other material, into static HTML.

* Dependencies

To build the website you need to install the Stack tool, we will use this to install all the dependencies required for site construction.

Information on Stack and how to install is availalbe online.

https://docs.haskellstack.org/en/stable/README/#how-to-install

Once stack is installed navigate to the project's root and run:

#+BEGIN_SRC sh
stack setup
#+END_SRC

* Building

We use a =Makefile= to make construction and deployment easy.

#+BEGIN_SRC sh
make build
#+END_SRC

The =Makefile= is a simple overlay for many Hakyll commands as executed using stack.

* Deployment

Deployment is achieved with the following =Makefile= command:

#+BEGIN_SRC sh
make deploy
#+END_SRC

This command builds the static site in =_site= and moves it to the =master= branch which github uses to publish the site.

Please note only those with a commit bit will be allowed to push to the site.

* References

Useful references for building and deploying with Hakyll and gh-pages include:

+ http://www.srid.ca/posts/2015-04-24-hakyll-and-circleci.html
+ http://jaspervdj.be/hakyll/
